import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { client } from '@/sanity/lib/client'
import { navigationQuery, settingsQuery } from '@/lib/queries'
import Header from '@/components/Header'
import type { Navigation, Settings } from '@/types/sanity'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ROOT LAYOUT
 *
 * This layout wraps every page in the application.
 * It's the perfect place to fetch site-wide data like
 * navigation and settings that appear on every page.
 *
 * Made async to fetch data from Sanity CMS.
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /**
   * FETCH SITE-WIDE DATA
   *
   * Navigation and settings are fetched here because:
   * - They appear on every page (in the header)
   * - Fetched once per page load and reused
   * - Server component - no client-side fetching needed
   * - Data is passed as props to Header component
   *
   * Promise.all fetches both in parallel for better performance.
   */
  const [navigation, settings] = await Promise.all([
    client.fetch<Navigation>(navigationQuery),
    client.fetch<Settings>(settingsQuery),
  ])

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Conditional rendering: only show Header if data exists */}
        {navigation && settings && (
          <Header navigation={navigation} settings={settings} />
        )}
        {children}
      </body>
    </html>
  );
}
