import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { client } from '@/sanity/lib/client'
import { navigationQuery, settingsQuery } from '@/lib/queries'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import type { Navigation, Settings } from '@/types/sanity'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ROOT LAYOUT
 *
 * This layout wraps every page in the application.
 * It's the perfect place to fetch site-wide data like
 * navigation and settings that appear on every page.
 *
 * Made async to fetch data from Sanity CMS.
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /**
   * FETCH SITE-WIDE DATA
   *
   * Navigation and settings are fetched here because:
   * - They appear on every page (in header and footer)
   * - Fetched once per page load and reused
   * - Server component - no client-side fetching needed
   * - Data is passed as props to Header and Footer components
   *
   * Promise.all fetches both in parallel for better performance.
   */
  const [navigation, settings] = await Promise.all([
    client.fetch<Navigation>(navigationQuery),
    client.fetch<Settings>(settingsQuery),
  ])

  return (
    <html lang="en">
      {/**
       * STICKY FOOTER LAYOUT
       *
       * flex flex-col min-h-screen: Makes body a flex column that fills viewport
       * This ensures footer sticks to bottom even on short pages.
       *
       * Structure:
       * - Header (auto height)
       * - Main content (flex-1 - grows to fill space)
       * - Footer (auto height, mt-auto pushes to bottom)
       */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Header - conditional rendering: only show if data exists */}
        {navigation && settings && (
          <Header navigation={navigation} settings={settings} />
        )}

        {/**
         * Main content area
         * flex-1: Grows to fill available space, pushing footer to bottom
         */}
        <main className="flex-1">
          {children}
        </main>

        {/**
         * Footer - conditional rendering: only show if settings exist
         * Footer only needs settings (for social links and copyright)
         * Navigation is not required for footer
         */}
        {settings && (
          <Footer settings={settings} />
        )}
      </body>
    </html>
  );
}
